use_frameworks!

target 'SirioLibanesApp_Example' do
  pod 'SirioLibanesApp', :path => '../'
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'PKHUD'
   pod 'BarcodeScanner'
   pod 'QRCode'

  target 'SirioLibanesApp_Tests' do
    inherit! :search_paths
  end
end
